@echo off
echo Transpiling 'src' into ES5 ...
echo ...
if exist dist (	
	rem rmdir /S /Q dist
)
call .\node_modules\.bin\babel --ignore tests,stories --plugins "transform-runtime" ./src --out-dir ./dist
echo ...
echo Transpiling completed.